### PR TITLE
Update docs to include overview of apptainer JupyterLab app

### PR DESCRIPTION
**Pull request by jaguillette**
This PR updates the documentation to include an overview of the JupyterLab (Apptainer) image, as well as some adjustments to the JupyterLab (Spack) docs to make them consistent with the new page. Each now includes a short description of how it differs from the other.

### CODE REVIEW

**Comment by jaguillette** [comment]
Per discussion after standup, will revise this PR to remove the spack jupyter setup docs.

**Comment by jaguillette** [comment]
Updates now all set to have apptainer implementation as the only jupyter one we have.

**Comment by arthurian** [comment]
:+1: Looks great (reviewed synchronously)!

**Review by Tanvez — APPROVED** [review]
LGMT!

**Comment by Tanvez** [comment]
also I found a link in `interactive-apps.md` that is linked to the removed `jupyterlab-spack.md`

**Comment by jaguillette** [comment]
Merged and updated on the live site with `mkdocs gh-deploy`

**Pull request merged**
